### ISSUE TITLE
Add to ubiome-opensource?

### ISSUE THREAD

**Issue by richardsprague** [jrrera/ubiome-to-d3#1]
Hi, 
Just saw your d3 conversion script.  Ubiome recently created the [ubiome-opensource repository](http://github.com/ubiome-opensource) to make it easy for people to find and share utilities like yours.  If you'd like to have yours included, please send us a pull request.

**Comment by jrrera** [comment]
Sure thing, Richard! I plan to polish up the code on this and I'll make a PR shortly after. Cheers.

**Comment by jrrera** [comment]
@richardsprague Would you prefer I simply update the README of ubiome-opensource to link to this repo, or move over a copy of the script? This is still under active development, so curious to hear your thoughts.

**Comment by richardsprague** [comment]
Go ahead and just update the README for now.

When you feel like it’s “done” (enough to call it a v1.0 or something) then submit a pull request for the whole repo and we’ll copy it over.

thanks!

**Comment by jrrera** [comment]
Done!
